name: Event Test
run-name: >-
  ${{ github.workflow }}

on:
  repository_dispatch:
    types: [codespace_awaken]


jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          echo "Inputs toJSON (raw block deserialized):"
          echo "${{ toJSON(inputs) }}"
          echo
          echo
          echo "---       1       ---"
          echo "First input raw:"
          echo
          echo "First input fromenv:"
          echo
          echo
          echo
          echo "---       2       ---"
          echo "Second input raw:"
          echo
          echo "Second input fromenv:"
          echo
          echo
          echo "---      ---      ---"
          echo
